language: python

python:
  - "2.7"

# command to install dependencies
install: ["pip install -r requirements.txt --use-mirrors", 'pip install pytest']

# command to run tests
script:
  - nosetests

after_success:
    - pip install coveralls
    - coverage run --source=flask_rbac setup.py nosetests
    - coveralls
